from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Capability:
    slug: str
    category: str
    name: str
    status: str
    test_file: str | None = None
    notes: str = ""
    api_mode: str = "chat"


def capability_suite(capability: Capability) -> str:
    if capability.test_file is None:
        return "unknown"
    parts = Path(capability.test_file).parts
    if len(parts) >= 3 and parts[0] == "tests":
        return parts[1]
    return "unknown"


def capability_expectation(capability: Capability) -> str:
    suite = capability_suite(capability)
    if suite == "effect":
        return "strict-pass"
    if suite == "contract":
        return "format-accurate"
    if suite == "acceptance":
        return "input-no-error"
    if suite == "probe":
        return "probe"
    return "unknown"


def find_capability(slug: str) -> Capability | None:
    for capability in CAPABILITIES:
        if capability.slug == slug:
            return capability
    return None


CAPABILITIES = [
    # Effect
    Capability(
        slug="chat-basic-non-stream",
        category="Basic Chat",
        name="Basic non-stream chat completion",
        status="covered",
        test_file="tests/effect/test_chat_basic_non_stream_live.py",
    ),
    Capability(
        slug="chat-basic-stream",
        category="Basic Chat",
        name="Basic streaming chat completion",
        status="covered",
        test_file="tests/effect/test_chat_basic_stream_live.py",
    ),
    Capability(
        slug="chat-tool-calling-non-stream",
        category="Tool Calling",
        name="Function/tool calling in non-stream mode",
        status="covered",
        test_file="tests/effect/test_chat_tools_non_stream_live.py",
    ),
    Capability(
        slug="chat-tool-calling-stream",
        category="Tool Calling",
        name="Function/tool calling in stream mode",
        status="covered",
        test_file="tests/effect/test_chat_tools_stream_live.py",
    ),
    Capability(
        slug="chat-tool-round-trip",
        category="Tool Calling",
        name="Tool call followed by tool result round-trip",
        status="covered",
        test_file="tests/effect/test_chat_tools_round_trip_live.py",
    ),
    Capability(
        slug="chat-tool-choice-named-multi",
        category="Tool Calling",
        name="Named tool choice with multiple available tools",
        status="covered",
        test_file="tests/effect/test_chat_tools_named_choice_multi_live.py",
    ),
    Capability(
        slug="chat-parallel-tool-calls",
        category="Tool Calling",
        name="Parallel tool call request compatibility",
        status="covered",
        test_file="tests/effect/test_chat_parallel_tool_calls_live.py",
    ),
    Capability(
        slug="tool-streaming-delta-arguments",
        category="Tool Streaming",
        name="Streaming tool_call deltas and partial argument assembly",
        status="covered",
        test_file="tests/effect/test_tool_streaming_delta_arguments_live.py",
    ),
    Capability(
        slug="chat-json-object-output",
        category="Structured Output",
        name="JSON object response format",
        status="covered",
        test_file="tests/effect/test_chat_response_format_json_object_live.py",
    ),
    Capability(
        slug="chat-json-schema-output",
        category="Structured Output",
        name="JSON schema constrained response format",
        status="covered",
        test_file="tests/effect/test_chat_response_format_json_schema_live.py",
    ),
    Capability(
        slug="chat-stop-semantic-effect",
        category="Sampling and Control",
        name="Stop sequence semantic truncation effect",
        status="covered",
        test_file="tests/effect/test_stop_effect_live.py",
    ),
    Capability(
        slug="chat-seed-determinism",
        category="Sampling and Control",
        name="Deterministic repeated output with seed",
        status="covered",
        test_file="tests/effect/test_chat_seed_consistency_live.py",
    ),
    Capability(
        slug="chat-penalty-controls",
        category="Sampling and Control",
        name="Frequency and presence penalty accepted by chat adapter",
        status="covered",
        test_file="tests/acceptance/test_chat_frequency_presence_penalty_live.py",
        notes="accepted by adapter; not counted as native semantic effect support",
    ),
    Capability(
        slug="chat-multiple-candidates",
        category="Sampling and Control",
        name="Multiple candidates via n completions",
        status="covered",
        test_file="tests/effect/test_chat_n_completions_live.py",
    ),
    Capability(
        slug="vision-base64-image",
        category="Vision",
        name="Vision with base64 image_url input",
        status="covered",
        test_file="tests/effect/test_vision_base64_live.py",
    ),
    Capability(
        slug="vision-generated-text-ocr",
        category="Vision",
        name="Vision OCR against a dynamically generated local image",
        status="covered",
        test_file="tests/effect/test_vision_generated_text_ocr_live.py",
    ),
    Capability(
        slug="vision-remote-image-url",
        category="Vision",
        name="Vision with remote image_url input",
        status="covered",
        test_file="tests/effect/test_vision_remote_url_live.py",
    ),
    Capability(
        slug="chat-input-audio",
        category="Multimodal Audio",
        name="Chat content parts with input_audio payloads",
        status="covered",
        test_file="tests/effect/test_chat_input_audio_live.py",
    ),
    Capability(
        slug="multi-turn-assistant-history",
        category="Conversation History",
        name="Assistant-message history priority in multi-turn chat",
        status="covered",
        test_file="tests/effect/test_history_assistant_priority_live.py",
    ),
    Capability(
        slug="content-array-mixed-parts",
        category="Content Shapes",
        name="Mixed content parts ordering (text + image + text)",
        status="covered",
        test_file="tests/effect/test_content_mixed_parts_order_live.py",
    ),
    Capability(
        slug="assistant-content-array-output",
        category="Content Shapes",
        name="Assistant content array output compatibility",
        status="covered",
        test_file="tests/effect/test_content_assistant_array_output_live.py",
    ),
    Capability(
        slug="developer-system-priority",
        category="Roles",
        name="developer vs system priority and precedence",
        status="covered",
        test_file="tests/effect/test_role_developer_system_priority_live.py",
    ),
    Capability(
        slug="tool-role-roundtrip-depth",
        category="Roles",
        name="Tool-role round-trip beyond the basic echo path",
        status="covered",
        test_file="tests/effect/test_role_tool_roundtrip_complex_live.py",
    ),
    Capability(
        slug="prompt-cache-hit-consistency",
        category="Prompt Caching",
        name="Prompt cache hit preserves semantic output consistency",
        status="covered",
        test_file="tests/effect/test_prompt_cache_hit_consistency_live.py",
    ),
    Capability(
        slug="concurrent-seed-consistency",
        category="Concurrency and Idempotency",
        name="Concurrent requests with the same seed remain deterministic",
        status="covered",
        test_file="tests/effect/test_concurrent_seed_consistency_live.py",
    ),
    # Contract
    Capability(
        slug="models-listing",
        category="Model Listing",
        name="List models via the OpenAI-compatible models endpoint",
        status="covered",
        test_file="tests/contract/test_models_live.py",
    ),
    Capability(
        slug="chat-prompt-cache-key",
        category="Basic Chat",
        name="Stable prompt cache key handling",
        status="covered",
        test_file="tests/contract/test_chat_prompt_cache_key_live.py",
    ),
    Capability(
        slug="chat-stop-parameter",
        category="Sampling and Control",
        name="Stop parameter acceptance",
        status="covered",
        test_file="tests/contract/test_chat_stop_sequences_live.py",
    ),
    Capability(
        slug="chat-logprobs",
        category="Sampling and Control",
        name="Logprobs and top_logprobs response compatibility",
        status="covered",
        test_file="tests/contract/test_chat_logprobs_live.py",
    ),
    Capability(
        slug="chat-stream-usage",
        category="Sampling and Control",
        name="Streaming usage blocks with include_usage",
        status="covered",
        test_file="tests/contract/test_chat_stream_include_usage_live.py",
    ),
    Capability(
        slug="chat-reasoning-effort",
        category="Sampling and Control",
        name="Reasoning effort parameter",
        status="covered",
        test_file="tests/contract/test_chat_reasoning_effort_live.py",
        notes="May be skipped when the selected model or backend does not support it.",
    ),
    Capability(
        slug="service-tier-roundtrip",
        category="Service Tier",
        name="service_tier request/response round-trip",
        status="covered",
        test_file="tests/contract/test_service_tier_roundtrip_live.py",
    ),
    Capability(
        slug="finish-reason-length",
        category="Finish Reasons",
        name="Explicit finish_reason coverage for length truncation",
        status="covered",
        test_file="tests/contract/test_finish_reason_length_live.py",
    ),
    Capability(
        slug="finish-reason-content-filter",
        category="Finish Reasons",
        name="Observed finish_reason behavior for content-filter-like refusals",
        status="covered",
        test_file="tests/probe/test_finish_reason_content_filter_live.py",
        notes="Probe only; many providers emit a refusal text with stop instead of content_filter.",
    ),
    Capability(
        slug="finish-reason-failure-surface",
        category="Finish Reasons",
        name="Failure-path behavior does not masquerade as a normal completion finish_reason",
        status="covered",
        test_file="tests/contract/test_finish_reason_error_state_live.py",
    ),
    Capability(
        slug="error-invalid-model",
        category="Errors and Boundaries",
        name="Invalid model handling",
        status="covered",
        test_file="tests/contract/test_error_invalid_model_live.py",
    ),
    Capability(
        slug="error-empty-messages",
        category="Errors and Boundaries",
        name="Empty messages handling",
        status="covered",
        test_file="tests/contract/test_error_empty_messages_live.py",
    ),
    Capability(
        slug="error-invalid-role",
        category="Errors and Boundaries",
        name="Invalid role handling",
        status="covered",
        test_file="tests/contract/test_error_invalid_role_live.py",
    ),
    Capability(
        slug="error-invalid-tool-schema",
        category="Errors and Boundaries",
        name="Invalid tool schema handling",
        status="covered",
        test_file="tests/contract/test_error_invalid_tool_schema_live.py",
    ),
    Capability(
        slug="error-invalid-response-schema",
        category="Errors and Boundaries",
        name="Invalid response schema handling",
        status="covered",
        test_file="tests/contract/test_error_invalid_response_schema_live.py",
    ),
    Capability(
        slug="error-timeout-runtime-shape",
        category="Errors and Boundaries",
        name="Timeout and runtime error surface compatibility",
        status="covered",
        test_file="tests/contract/test_error_timeout_runtime_shape_live.py",
        notes="Uses a very small client timeout to verify timeout surfacing through the official SDK.",
    ),
    Capability(
        slug="streaming-first-chunk-role",
        category="Streaming Semantics",
        name="Role emitted only on the first streaming chunk",
        status="covered",
        test_file="tests/contract/test_stream_first_chunk_role_live.py",
    ),
    Capability(
        slug="streaming-chunk-order",
        category="Streaming Semantics",
        name="Streaming chunk ordering remains stable",
        status="covered",
        test_file="tests/contract/test_stream_chunk_order_live.py",
    ),
    Capability(
        slug="streaming-terminal-chunk-shape",
        category="Streaming Semantics",
        name="Terminal streaming chunk shape matches OpenAI semantics",
        status="covered",
        test_file="tests/contract/test_stream_terminal_chunk_shape_live.py",
    ),
    Capability(
        slug="stream-interruption-retry",
        category="Streaming Semantics",
        name="Streaming interruption and retry semantics",
        status="covered",
        test_file="tests/contract/test_stream_interruption_retry_live.py",
    ),
    Capability(
        slug="usage-token-arithmetic",
        category="Usage Accounting",
        name="Prompt/completion/total token arithmetic consistency",
        status="covered",
        test_file="tests/contract/test_usage_token_arithmetic_live.py",
    ),
    Capability(
        slug="usage-content-scale",
        category="Usage Accounting",
        name="Prompt and completion token counts scale with content size",
        status="covered",
        test_file="tests/contract/test_usage_content_scale_live.py",
    ),
    # Probe
    Capability(
        slug="service-tier-latency-probe",
        category="Service Tier",
        name="service_tier latency probe",
        status="covered",
        test_file="tests/probe/test_service_tier_latency_probe_live.py",
    ),
    Capability(
        slug="prompt-cache-latency-usage",
        category="Prompt Caching",
        name="Prompt cache latency and usage observability probe",
        status="covered",
        test_file="tests/probe/test_prompt_cache_latency_usage_live.py",
        notes="Probe-oriented test; it records observability rather than asserting absolute latency improvement.",
    ),
    # Acceptance-only planned exception
    Capability(
        slug="chat-logit-bias-semantic",
        category="Sampling and Control",
        name="Acceptance-only logit_bias validation",
        status="covered",
        test_file="tests/acceptance/test_chat_logit_bias_live.py",
        notes="Validates request acceptance and normal response shape only; it does not assert semantic effect.",
    ),
    Capability(
        slug="chat-temperature-acceptance",
        category="Sampling and Control",
        name="Acceptance-only temperature validation",
        status="covered",
        test_file="tests/acceptance/test_chat_temperature_live.py",
        notes="Validates request acceptance and normal response shape only; it does not assert semantic temperature effect.",
    ),
    Capability(
        slug="responses-metadata-compat-gap-error",
        category="Responses Acceptance",
        name="Metadata compat gap error",
        status="covered",
        test_file="tests/acceptance/test_responses_metadata_compat_gap_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-parallel-tool-calls-false",
        category="Responses Acceptance",
        name="Parallel tool calls false",
        status="covered",
        test_file="tests/acceptance/test_responses_parallel_tool_calls_false_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-prompt-cache-key-acceptance",
        category="Responses Acceptance",
        name="Prompt cache key acceptance",
        status="covered",
        test_file="tests/acceptance/test_responses_prompt_cache_key_acceptance_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-service-tier-compat-gap-error",
        category="Responses Acceptance",
        name="Service tier compat gap error",
        status="covered",
        test_file="tests/acceptance/test_responses_service_tier_compat_gap_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-text-verbosity",
        category="Responses Acceptance",
        name="Text verbosity",
        status="covered",
        test_file="tests/acceptance/test_responses_text_verbosity_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-tool-choice-required",
        category="Responses Acceptance",
        name="Tool choice required",
        status="covered",
        test_file="tests/acceptance/test_responses_tool_choice_required_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-top-p-compat-gap-error",
        category="Responses Acceptance",
        name="Top p compat gap error",
        status="covered",
        test_file="tests/acceptance/test_responses_top_p_compat_gap_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-truncation-compat-gap-error",
        category="Responses Acceptance",
        name="Truncation compat gap error",
        status="covered",
        test_file="tests/acceptance/test_responses_truncation_compat_gap_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-user-compat-gap-error",
        category="Responses Acceptance",
        name="User compat gap error",
        status="covered",
        test_file="tests/acceptance/test_responses_user_compat_gap_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-default-instructions",
        category="Responses Contract",
        name="Default instructions",
        status="covered",
        test_file="tests/contract/test_responses_default_instructions_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-developer-hoist",
        category="Responses Contract",
        name="Developer hoist",
        status="covered",
        test_file="tests/contract/test_responses_developer_hoist_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-empty-input-error",
        category="Responses Contract",
        name="Empty input error",
        status="covered",
        test_file="tests/contract/test_responses_empty_input_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-explicit-instructions-override-hoisted-roles",
        category="Responses Contract",
        name="Explicit instructions override hoisted roles",
        status="covered",
        test_file="tests/contract/test_responses_explicit_instructions_override_hoisted_roles_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-invalid-input-item-type-error",
        category="Responses Contract",
        name="Invalid input item type error",
        status="covered",
        test_file="tests/contract/test_responses_invalid_input_item_type_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-invalid-temperature-error",
        category="Responses Contract",
        name="Invalid temperature error",
        status="covered",
        test_file="tests/contract/test_responses_invalid_temperature_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-invalid-token-limit-error",
        category="Responses Contract",
        name="Invalid token limit error",
        status="covered",
        test_file="tests/contract/test_responses_invalid_token_limit_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-invalid-tool-schema-error",
        category="Responses Contract",
        name="Invalid tool schema error",
        status="covered",
        test_file="tests/contract/test_responses_invalid_tool_schema_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-json-object-text-format",
        category="Responses Contract",
        name="Json object text format",
        status="covered",
        test_file="tests/contract/test_responses_json_object_text_format_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-json-object-without-json-prompt-error",
        category="Responses Contract",
        name="Json object without json prompt error",
        status="covered",
        test_file="tests/contract/test_responses_json_object_without_json_prompt_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-non-stream-and-stream-minimum-consistency",
        category="Responses Contract",
        name="Non stream and stream minimum consistency",
        status="covered",
        test_file="tests/contract/test_responses_non_stream_and_stream_minimum_consistency_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-previous-response-id-branch-fork",
        category="Responses Contract",
        name="Previous response id branch fork",
        status="covered",
        test_file="tests/contract/test_responses_previous_response_id_branch_fork_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-previous-response-id-branch-idempotence",
        category="Responses Contract",
        name="Previous response id branch idempotence",
        status="covered",
        test_file="tests/contract/test_responses_previous_response_id_branch_idempotence_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-previous-response-id-continuation",
        category="Responses Contract",
        name="Previous response id continuation",
        status="covered",
        test_file="tests/contract/test_responses_previous_response_id_continuation_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-previous-response-id-function-call-output",
        category="Responses Contract",
        name="Previous response id function call output",
        status="covered",
        test_file="tests/contract/test_responses_previous_response_id_function_call_output_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-previous-response-id-streamed-function-call-output",
        category="Responses Contract",
        name="Previous response id streamed function call output",
        status="covered",
        test_file="tests/contract/test_responses_previous_response_id_streamed_function_call_output_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-reasoning-effort",
        category="Responses Contract",
        name="Reasoning effort",
        status="covered",
        test_file="tests/contract/test_responses_reasoning_effort_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-streaming-event-closure",
        category="Responses Contract",
        name="Streaming event closure",
        status="covered",
        test_file="tests/contract/test_responses_streaming_event_closure_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-streaming-invalid-input-item-type-error",
        category="Responses Contract",
        name="Streaming invalid input item type error",
        status="covered",
        test_file="tests/contract/test_responses_streaming_invalid_input_item_type_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-streaming-partial-consumption",
        category="Responses Contract",
        name="Streaming partial consumption",
        status="covered",
        test_file="tests/contract/test_responses_streaming_partial_consumption_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-system-and-developer-precedence",
        category="Responses Contract",
        name="System and developer precedence",
        status="covered",
        test_file="tests/contract/test_responses_system_and_developer_precedence_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-system-hoist",
        category="Responses Contract",
        name="System hoist",
        status="covered",
        test_file="tests/contract/test_responses_system_hoist_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-temperature-and-token-limits-are-accepted",
        category="Responses Contract",
        name="Temperature and token limits are accepted",
        status="covered",
        test_file="tests/contract/test_responses_temperature_and_token_limits_are_accepted_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-temperature-two",
        category="Responses Contract",
        name="Temperature two",
        status="covered",
        test_file="tests/contract/test_responses_temperature_two_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-temperature-zero",
        category="Responses Contract",
        name="Temperature zero",
        status="covered",
        test_file="tests/contract/test_responses_temperature_zero_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-unknown-previous-response-id-error",
        category="Responses Contract",
        name="Unknown previous response id error",
        status="covered",
        test_file="tests/contract/test_responses_unknown_previous_response_id_error_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-assistant-history",
        category="Responses Effect",
        name="Assistant history",
        status="covered",
        test_file="tests/effect/test_responses_assistant_history_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-basic-create",
        category="Responses Effect",
        name="Basic create",
        status="covered",
        test_file="tests/effect/test_responses_basic_create_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-basic-stream",
        category="Responses Effect",
        name="Basic stream",
        status="covered",
        test_file="tests/effect/test_responses_basic_stream_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-image-input",
        category="Responses Effect",
        name="Image input",
        status="covered",
        test_file="tests/effect/test_responses_image_input_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-message-array-input",
        category="Responses Effect",
        name="Message array input",
        status="covered",
        test_file="tests/effect/test_responses_message_array_input_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-non-stream-aggregation",
        category="Responses Effect",
        name="Non stream aggregation",
        status="covered",
        test_file="tests/effect/test_responses_non_stream_aggregation_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-string-input",
        category="Responses Effect",
        name="String input",
        status="covered",
        test_file="tests/effect/test_responses_string_input_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-system-plus-assistant-history",
        category="Responses Effect",
        name="System plus assistant history",
        status="covered",
        test_file="tests/effect/test_responses_system_plus_assistant_history_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-tool-call-non-stream",
        category="Responses Effect",
        name="Tool call non stream",
        status="covered",
        test_file="tests/effect/test_responses_tool_call_non_stream_live.py",
        api_mode="responses",
    ),
    Capability(
        slug="responses-tool-call-stream",
        category="Responses Effect",
        name="Tool call stream",
        status="covered",
        test_file="tests/effect/test_responses_tool_call_stream_live.py",
        api_mode="responses",
    ),
]
